FROM node:20-alpine

WORKDIR /app/backend

COPY backend/package*.json ./
COPY backend/prisma ./prisma

RUN npm install

COPY backend/ ./

RUN npx prisma generate
RUN npm run build

EXPOSE 4000

CMD ["sh", "-c", "npx prisma migrate deploy || npx prisma db push && npm run db:seed && node dist/server.js"]
